sudo: false
os:
 - linux
 - osx
language: d
d:
 - dmd
 - ldc
 - dmd-2.083.0
 - ldc-1.12.0
env:
 - ARCH="x86_64" CONF=""
 - ARCH="x86_64" CONF="-sse42"
 - ARCH="AARCH64" CONF=""
matrix:
  include:
    - {os: linux, d: dmd-2.083.0, env: ARCH="x86" CONF="", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-1.12.0, env: ARCH="x86" CONF="", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-1.12.0, env: ARCH="x86" CONF="-sse42", addons: {apt: {packages: [[gcc-multilib]]}}}
branches:
  only:
    - master
services:
  - docker
script:
  - if [ $ARCH -eq "AARCH64" ]
    then
      docker run --rm --privileged multiarch/qemu-user-static:register --reset
      docker build -t asdf-arm64 . -f Dockerfile.aarch64
    else
      echo $ARCH
      dub test --arch=$ARCH --build=unittest$CONF
      cd benchmarks/sajson ; dub --build=release-nobounds --compiler=ldmd2 ; cd ../..
    fi
after_success:
 - bash <(curl -s https://codecov.io/bash)
