os:
 - linux
 - osx

language: d
d:
 - dmd
 - ldc
 - dmd-2.095.1
 - ldc-1.25.0

env:
 - ARCH="x86_64"

matrix:
  include:
    - os: linux
      d: ldc-1.23.0
      env: ARCH="AARCH64"
      arch: arm64
    - os: linux
      d: dmd-2.093.1
      env: ARCH="x86"
      addons:
      - apt:
        - packages: gcc-multilib
    - os: linux
      d: ldc-1.23.0
      env: ARCH="x86"
      addons: 
      - apt:
        - packages: gcc-multilib

branches:
  only:
    - master

script: bash -e test_travis.sh
after_success:
 - bash <(curl -s https://codecov.io/bash)
