version: 2.1

jobs:
  test_example:
    docker:
      - image: libmir/circle-dlang
    steps:
      - checkout
      - run:
          name: Test meson example
          command: |
            cd meson-example
            meson build --default-library=static --buildtype=debug
            ninja -C build
            gcc test.c build/libion_meson_example.so
            LD_LIBRARY_PATH=build ./a.out
            dub build -c bloomberg

orbs:
  mirci: libmir/upload_docs@0.1.4

workflows:
  version: 2
  build-deploy:
    jobs:
      - test_example
      - mirci/test_and_build_docs:
          filters:
            tags:
              only: /^v(\d)+(\.(\d)+)+$/
      - mirci/upload_docs:
          to: mir-ion.libmir.org
          requires:
            - mirci/test_and_build_docs
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(\d)+(\.(\d)+)+$/
